language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_install:
  - sudo apt-get install libpng-dev
  - sudo apt-get install nasm
  - npm install -g firebase-tools
  - npm install -g hexo
install:
  - npm install
before_script:
  - sudo chown -R 700 /etc/couchdb/local.d
script:
  - hexo clean
  - hexo generate
after_success:
  - firebase deploy --token $FIREBASE_TOKEN