language: node_js
node_js:
  - "10"
branches:
  only:
  - master
before_install:
  - sudo apt-get install libpng-dev
  - npm install -g firebase-tools
  - npm install -g hexo
install:
  - npm install
script:
  - hexo generate
after_success:
  - firebase deploy --token $FIREBASE_TOKEN