
language: node_js
node_js:
- "9"

branches:
  only:
  - master

before_install:
- npm install -g hexo
- npm install -g firebase-tools
- npm install

before_script:
- git config --global user.name 'Lee Boonstra'
- git config --global user.email 'me@leeboonstra.com'

script:
- hexo generate

after_success:
— firebase deploy — project $FIREBASE_PROJECT $FIREBASE_TOKEN.
