
language: node_js
node_js:
- "9"
branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
  - npm install -g hexo
before_script:
- git config --global user.name 'Lee Boonstra'
- git config --global user.email 'me@leeboonstra.com'
install:
  - npm install
script:
- hexo generate
after_success:
- firebase deploy --token $FIREBASE_TOKEN