# Hexo Configuration
## Docs: https:/hexo.io/docs/configuration.html
## Source: https:/github.com/hexojs/hexo/

# Site
title: LeeBoonstra.com | DevTricks for developers
subtitle: <span>"</span> <span>Hi my name is <b>Lee</b>.</span><br><span>I'm a writer an engineer a trainer and a public speaker.</span><br> <span>I create fixes & I fix headaches...</span><br> <span>Welcome to my <b>dev blog</b>.</span><span>"</span>
description: Developer blog of sales engineer & Googler Lee Boonstra. Ex Sencha trainer. Shares Google Cloud Platform, Machine Learning, Chatbots, Dialogflow & Ext JS tips. O'Reilly book author of the book Hands-on Sencha Touch 2 and public speaker.
keywords: Googler, Dialogflow, JavaScript, Ext JS, Sencha Touch, Cordova, Chatbots, Machine Learning, AI, ML, Cloud, GCP, Public Cloud, Ext JS engineer, Google Sales Engineer, Public Speaker, Google Customer Engineer, Googler Engineer, Sencha Sales Engineer, Sencha Trainer, Dev-ops, Dev-ops Specialist, Public Speaker, Machine Learning Public Speaker, Cloud Architect, Devrel, Developer Relations, Developer Expert, Chatbot expert, Actions on Google, Dialogflow expert, Google Cloud Sales, GCP Engineer, Sencha Trainings, JavaScript Developer, Front-end Developer, Lead front-end developer, Client-side Developer, O'Reilly book author, JavaScript Programmer, Node JS Developer, Client-side code, Lead Developer JavaScript Amsterdam, JavaScript Evangelist, Google Assistant Expert, Chatbot Expertise, Chatbot Help, Cloud Help, GCP Help, Google Cloud Solutions, Google Cloud Consultant, Dialogflow Enterprise, Bots Chat agents, HTML5 & CSS3, Sencha Touch Mobile Apps, Enterprise App developer
author: Lee Boonstra
language: en
timezone: Europe/Amsterdam

# URL
## If your site is put in a subdirectory set url as 'http:/yoursite.com/child' and root as '/child/'
url: https://www.leeboonstra.com/
root: /
permalink: :category/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

#Header
navbar_brand: false
menu:
  Home: index.html
  About: about/
  Speaking: speaking/
  Writing: writing/
  Videos: /categories/Videos/
  Contact: contact/
rss: /atom.xml

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http:/momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https:/hexo.io/plugins/
## Themes: https:/hexo.io/themes/
theme: ladysign

# Deployment
## Docs: https:/hexo.io/docs/deployment.html
deploy:
  type:

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- category
- archive
- recent_posts

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: 'UA-85081556-1'

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

disqus_enabled: true
disqus_shortname: leeboonstra-com

sitemap:
    path: sitemap.xml

marked:
  gfm: true
  sanitize: false
  tables: true
  breaks: false
  autolink: true


css_minifier:
  enable: true
  silent: false
  exclude: 
      - '/*.min.css'

js_minifier:
  enable: true
  mangle: true
  silent: false
  output:
  compress:
  exclude: 
      - '/*.min.js'

html_minifier:
  enable: true
  ignore_error: false
  silent: false
  exclude:

image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false